spaces = ' ' * 25
print()
print()
print()
print('%s Pretty Guardian of Love and Justice' % spaces)
print('%s 123 Mermaid Avenue' % spaces)
print('%s Juban, Tokyo JP' % spaces)
print()
print()
print('Dear Serena Tsukino')
print()
print('It has been a while since we had the chance to chat!')
print('I look forward to seeing you and the girls very soon.')
print('Please do not forget to feed the talking cat.')
print()
print()
print('May the moonlight lead the way,')
print('Milena')
